#define MOUSEKEY_INTERVAL 33
#define MOUSEKEY_MAX_SPEED 20
#define MOUSEKEY_MOVE_DELTA 1
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_VAL 0
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define TAPPING_TOGGLE 2
#define ONESHOT_TAP_TOGGLE 2
