#pragma once

#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_VAL 0

#define TAPPING_TERM 300

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
    #undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 9

#undef  COCOT_CPI_DEFAULT
#define COCOT_CPI_DEFAULT 2

#undef COCOT_CPI_OPTIONS
#define COCOT_CPI_OPTIONS { 250, 500, 750, 1000, 1625 }

#undef  COCOT_ROTATION_DEFAULT
#define COCOT_ROTATION_DEFAULT 4
